version: '3.8'
services:
  test-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: brightboost_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

volumes:
  test_postgres_data:
