#!/bin/sh
echo "===================================================================================================="
echo "  ERROR: package-lock.json is out of date or invalid."
echo "  The build failed because 'npm ci' rejected the current lockfile."
echo ""
echo "  TO FIX THIS:"
echo "  1. Run the following commands locally to update the lockfile:"
echo "       npm install"
echo ""
echo "  2. Commit the updated package-lock.json file:"
echo "       git add package-lock.json"
echo "       git commit -m 'chore: update npm lockfile'"
echo "       git push"
echo ""
echo "  This ensures reproducible builds in Railway/Docker."
echo "===================================================================================================="
