#!/bin/sh
echo "===================================================================================================="
echo "  ERROR: pnpm-lock.yaml is out of date or invalid."
echo "  The build failed because 'pnpm install --frozen-lockfile' rejected the current lockfile."
echo ""
echo "  TO FIX THIS:"
echo "  1. Run the following commands locally to update the lockfile:"
echo "       corepack enable"
echo "       corepack prepare pnpm@9.15.1 --activate"
echo "       pnpm install"
echo ""
echo "  2. Commit the updated pnpm-lock.yaml file:"
echo "       git add pnpm-lock.yaml"
echo "       git commit -m 'chore: update pnpm lockfile'"
echo "       git push"
echo ""
echo "  This ensures reproducible builds in Railway/Docker."
echo "===================================================================================================="
