name: BrightBoost – Production SWA (Canonical)
# This is the single canonical production deployment workflow for BrightBoost.
# All production deployments should use this workflow only.
# Updated to fix Azure SWA placeholder page issue
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_BAY_0BFACC110 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          deployment_environment: "production"
          skip_api_build: true
          app_location: "/"
          api_location: ""
          output_location: "dist"
