name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: [ main ]

jobs:
  swa:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install deps
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Build frontend (Vite)
        working-directory: frontend
        env:
          # point the SPA to the live/staging API
          VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
        run: pnpm build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: frontend        # folder with your SPA source
          output_location: dist         # built assets from the step above
          skip_app_build: true          # we've already built with pnpm
