name: Lambda Diagnostics - Tail Login & Signup Handler Logs

on:
  workflow_dispatch:

jobs:
  diagnose-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Tail Lambda logs
        run: |
          aws logs tail '/aws/lambda/brightboost-auth-prod-login-fn' --since 10m > login_logs.txt &
          aws logs tail '/aws/lambda/brightboost-auth-prod-student-fn' --since 10m > signup_logs.txt &
          sleep 60 && pkill -f "aws logs tail"
          echo "=== LOGIN HANDLER LOGS ===" && cat login_logs.txt
          echo "=== SIGNUP HANDLER LOGS ===" && cat signup_logs.txt
